<a href="https://colab.research.google.com/github/LailaBulh/Procesamiento_Lenguaje_Natural/blob/main/Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nombre:** Laila Montserrat Bulhosen Ramos Matricula: 263166

**Docente:** Dr. Rogelio Florencia Juarez

**Materia:** Procesamiento de Lenguaje

**Objetivo:** Explorar la representación semántica de palabras e identifica los diferentes dominios temáticos contenidos en el conjunto de datos proporcionado mediante la visualización 2D de embeddings de palabras.

**Link Github:** [Representacion de texto - Embeddings](https://github.com/LailaBulh/Procesamiento_Lenguaje_Natural/blob/main/Embeddings.ipynb)

**Fecha:** 14 marzo 2026

In [1]:
### Coneccion Google driver
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
### Librerias necesasrias
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

In [3]:
!pip install unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.12/dist-packages (1.4.0)

In [4]:
from unidecode import unidecode

In [11]:
pd.set_option('display.width', 200)

In [12]:
### Import CSV
text = pd.read_csv('/content/drive/MyDrive/Procesamiento Lenguaje Natural/Ejercicios de Representación de textos - Embeddings.csv')

display(text)

                                                 frase
0    La ciberseguridad protege la información digit...
1    La inteligencia artificial transforma múltiple...
2    El baloncesto combina velocidad, técnica y tra...
3    El hardware y el software son complementarios ...
4    La democracia permite la participación ciudada...
..                                                 ...
143  La natación es una disciplina que fortalece to...
144  Los atletas requieren entrenamiento constante ...
145  Las políticas públicas buscan atender necesida...
146  Los partidos políticos representan diferentes ...
147  Las políticas públicas buscan atender necesida...

[148 rows x 1 columns]

In [9]:
### Convertir a minúsculas
text = text['frase'].str.lower()
display(text)

KeyError: 'frase'

In [14]:
### Eliminar puntuaciones
text = text.apply(lambda x: re.sub(r'[^\w\s]', '', x))

#display(text)

TypeError: expected string or bytes-like object, got 'Series'

In [11]:
#display(text)

0             la ciberseguridad protege la información digit...
1             la inteligencia artificial transforma múltiple...
2             el baloncesto combina velocidad, técnica y tra...
3             el hardware y el software son complementarios ...
4             la democracia permite la participación ciudada...
                                    ...
144           los atletas requieren entrenamiento constante ...
145           las políticas públicas buscan atender necesida...
146           los partidos políticos representan diferentes ...
147           las políticas públicas buscan atender necesida...
puntuacion    0
1
2     ...
Name: frase, Length: 149, dtype: object

In [16]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [7]:
#text_all = ' '.join(text['puntuacion'].tolist())
#print(text_all)

#tokens = word_tokenize(text_all, language= 'spanish')
#print(tokens)